language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  global:
    secure: "H2OUtWjug6nutKAQ8CACT4WOWfSqJLIqdegCSxH+VFs+Ia6kbedJ1Q8BWaECtOCdSJ/9oQvLSDUBjFozRuY2V052/Xsi3XICtqPYDGgeBgyE6GvyDarjNud4tKcUra9YCxddPlQwYKpsxCj4Qa3m4HZet8RsTIuiNttwHepenco="

before_install:
  - sudo apt-get install -qq pandoc
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -n condaenv pip
  - source activate condaenv
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - conda install -c obspy python=3.4 obspy --yes
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pytest flake8 sphinx ipython-notebook mpi4py pandas future pygments jinja2
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install --use-mirrors sphinx-readable-theme mistune runipy; fi
  - pip install coveralls

install:
  - pip install --no-deps -v -e .

script:
  - coverage run --source=src/wfdiff -m wfdiff.tests
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then cd $TRAVIS_BUILD_DIR/doc; make html ; fi

after_success:
  - cd $TRAVIS_BUILD_DIR; coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then bash $TRAVIS_BUILD_DIR/.travis-update-gh-pages.sh ; fi
